# Generated by Django 4.1.5 on 2023-03-15 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_total_price', models.FloatField(default=0.0)),
                ('basket_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Category_totoal_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, unique=True)),
                ('customer_Birth_date', models.CharField(max_length=30)),
                ('customer_Mobile_number', models.CharField(max_length=15)),
                ('customer_gender', models.CharField(max_length=4)),
                ('custome_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_description', models.CharField(max_length=500)),
                ('Product_counter', models.IntegerField(default=0)),
                ('Product_price', models.FloatField()),
                ('Product_image', models.ImageField(null=True, upload_to='')),
                ('product_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_stars', models.IntegerField()),
                ('rating_description', models.CharField(max_length=100)),
                ('product_rating_customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customers')),
                ('product_rating_product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_datails_vat', models.FloatField()),
                ('bill_datails_final_price', models.FloatField()),
                ('bill_details_counter', models.IntegerField()),
                ('bill_details_date', models.CharField(max_length=255)),
                ('bill_details_bill_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_customer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customers'),
        ),
        migrations.CreateModel(
            name='Basket_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_datails_product_price', models.FloatField()),
                ('basket_details_product_count', models.IntegerField(default=0)),
                ('basket_details_basket_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.basket')),
                ('basket_details_product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_customer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customers'),
        ),
    ]
