# Generated by Django 4.1.5 on 2023-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_email',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
