# Generated by Django 4.1.5 on 2023-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customers_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(default='apple', max_length=500),
            preserve_default=False,
        ),
    ]
