# Generated by Django 4.1.5 on 2023-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_description',
            field=models.CharField(max_length=1000),
        ),
    ]
