# Generated by Django 4.1.5 on 2023-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
