# Generated by Django 4.1.5 on 2023-03-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_description',
            field=models.CharField(max_length=10000),
        ),
    ]
