# Generated by Django 4.0.4 on 2023-04-06 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
