# Generated by Django 4.0.4 on 2023-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_after_discount',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_before_discount',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
