# Generated by Django 4.0.4 on 2023-04-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_offer_offer_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
