# Generated by Django 4.0.4 on 2023-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_shippinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='bill_datails_vat',
            field=models.FloatField(default=1.0),
        ),
    ]
