# Generated by Django 4.0.4 on 2023-04-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_order_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
