# Generated by Django 4.0.4 on 2023-04-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_order_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
    ]
