# Generated by Django 4.0.4 on 2023-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_product_rating_product_rating_customer_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
